# Generated by Django 6.0.5 on 2026-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('EmpresaID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('paquete', models.CharField(choices=[('seguridad', 'Seguridad'), ('auxiliares', 'Auxiliares'), ('mantenimiento', 'Mantenimiento'), ('transportes', 'Transportes')], default=None, max_length=20)),
            ],
        ),
    ]
