# Generated by Django 6.0.5 on 2026-06-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicios',
            field=models.ManyToManyField(related_name='clientes', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='user_client',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacion', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='user_client',
            name='servicios',
            field=models.ManyToManyField(related_name='usuarios_cliente', to='servicios.servicio'),
        ),
    ]
