# Generated by Django 6.0.5 on 2026-06-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cif_enc_cliente_direccion_enc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cif',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
