# Generated by Django 6.0.5 on 2026-06-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_cif_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cif_enc',
            new_name='cif',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion_enc',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email_enc',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono_enc',
            new_name='telefono',
        ),
    ]
