# Generated by Django 6.0.5 on 2026-07-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediosaux', '0001_initial'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioauxiliar',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediosaux', to='users.cuenta'),
        ),
    ]
