# Generated by Django 6.0.5 on 2026-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartado', models.CharField(choices=[('TAREA', 'Tarea'), ('LOGIN', 'Login'), ('USER', 'Usuario'), ('EMPRESA', 'Empresa'), ('SERVICIO', 'Servicio'), ('ALMACEN', 'Almacen'), ('CENTRAL', 'Central Receptora'), ('CLIENTE', 'Cliente'), ('PARTE', 'Parte'), ('DELEGACION', 'Delegacion'), ('MANTENIMIENTO', 'Mantenimiento'), ('MEDIO-AUX', 'Medios auxiliares'), ('SUGERENCIA', 'Sugerencia')], max_length=20)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('REMOVE', 'Borrar'), ('UPDATE', 'Editar'), ('DELETE', 'Eliminar'), ('AUTH', 'Autenticacion')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_cuenta', models.IntegerField(blank=True, null=True)),
                ('id_usuario_cliente', models.IntegerField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('cuenta_id', models.IntegerField(blank=True, null=True)),
                ('ip_sesion', models.GenericIPAddressField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=30, null=True)),
                ('browser_name_version', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
