# Generated by Django 6.0.5 on 2026-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditloggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('REMOVE', 'Borrar'), ('UPDATE', 'Editar'), ('DELETE', 'Eliminar'), ('AUTH', 'Autenticacion'), ('UNAUTH', 'No autorizado'), ('ERROR', 'Error'), ('PERMISSION', 'Cambio de permisos'), ('OUT', 'Cierre de sesion')], max_length=20),
        ),
    ]
