# Generated by Django 6.0.5 on 2026-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditloggers', '0002_alter_auditlog_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='extra_info',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
