# Generated by Django 6.0.5 on 2026-07-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen_item',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacen_items', to='users.cuenta'),
        ),
    ]
