# Generated by Django 6.0.5 on 2026-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('TareaID', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('leida', 'Leída'), ('en_progreso', 'En progreso'), ('terminada', 'Terminada'), ('borrada', 'Borrada')], default='pendiente', max_length=20)),
                ('tipo_asociacion', models.CharField(choices=[('empresa', 'Asociada a todos los usuarios de una empresa'), ('usuario', 'Asociada a usuario particular')], default='usuario', max_length=20)),
                ('es_urgente', models.BooleanField(default=False)),
                ('empresas_asociadas', models.ManyToManyField(related_name='tareas_asociadas', to='empresas.empresa')),
            ],
        ),
    ]
