# Generated by Django 6.0.5 on 2026-06-18 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_servicio_asignado_alter_tarea_usuario_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('usuarios', models.ManyToManyField(related_name='listados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
