# Generated by Django 6.0.5 on 2026-05-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('CentralID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('persona_de_contacto', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
