# Generated by Django 6.0.5 on 2026-06-25 09:10

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centrales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='central',
            name='mail_enc',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='central',
            name='telefono_enc',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
