# Generated by Django 6.0.5 on 2026-06-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centrales', '0003_central_mail_enc_central_telefono_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='central',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='central',
            name='telefono',
        ),
    ]
