# Generated by Django 6.0.5 on 2026-06-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centrales', '0004_remove_central_mail_remove_central_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='mail_enc',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='central',
            old_name='telefono_enc',
            new_name='telefono',
        ),
    ]
