# Generated by Django 6.0.5 on 2026-06-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrales', '0005_rename_mail_enc_central_mail_and_more'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='central',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centrales', to='users.cuenta'),
        ),
    ]
