# Generated by Django 6.0.5 on 2026-05-26 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(choices=[('ejecutivo', 'Ejecutivo'), ('comercial', 'Comercial'), ('operario', 'Operario'), ('administrativo', 'Administrativo')], default='ejecutivo', max_length=20)),
                ('has_login_access', models.BooleanField(default=True)),
                ('has_dashboard_access', models.BooleanField(default=False)),
                ('permisos_usuario', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_tareas', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_clientes', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_servicios_NFC', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_central_receptora', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_medios_auxiliares', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_sugerencias', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_partes_trabajo', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('can_view_own_partes_trabajo', models.BooleanField(default=False)),
                ('permisos_partes_incidencias', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_informes_acuda', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_partes_inspeccion', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_mantenimientos', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_almacen', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_informes', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_empresas', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('permisos_configuracion', models.CharField(choices=[('no_access', 'Sin acceso'), ('view_only', 'Puede ver'), ('create_modify', 'Puede crear y modificar')], default='no_access', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
