# Generated by Django 6.0.5 on 2026-06-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0001_initial'),
        ('servicios', '0001_initial'),
        ('users', '0002_alter_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='delegaciones.delegacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='servicios',
            field=models.ManyToManyField(related_name='users', to='servicios.servicio'),
        ),
    ]
