# Generated by Django 6.0.5 on 2026-06-23 10:29

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delegacion_user_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to=users.models.set_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
