# Generated by Django 6.0.5 on 2026-06-24 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cuadrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrante',
            name='fecha_borrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadrante',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
