# Generated by Django 6.0.5 on 2026-06-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cuadrante_fecha_borrado_cuadrante_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('USR', 'Usuarios'), ('TAR', 'Tareas'), ('CLI', 'Clientes'), ('NFC', 'Servicios NFC'), ('CEN', 'Central Receptora'), ('MED', 'Medios Auxiliares'), ('SUG', 'Sugerencias'), ('PAR', 'Partes Trabajo'), ('INC', 'Partes Incidencias'), ('ACU', 'Informes Acuda'), ('INS', 'Partes Inspección'), ('MAN', 'Mantenimientos'), ('ALM', 'Almacén'), ('INF', 'Informes'), ('EMP', 'Empresas'), ('CON', 'Configuración')], max_length=3)),
                ('nivel', models.CharField(choices=[('0', 'Sin acceso'), ('1', 'Lectura'), ('2', 'Escritura'), ('3', 'Admin')], default='0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
