# Generated by Django 6.0.5 on 2026-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permisosmodulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisosmodulo',
            name='nivel',
            field=models.CharField(choices=[('0', 'Sin acceso'), ('1', 'Lectura'), ('2', 'Escritura')], default='0', max_length=1),
        ),
    ]
