# Generated by Django 6.0.5 on 2026-06-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_permisosmodulo_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permisos_almacen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_central_receptora',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_clientes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_configuracion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_empresas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_informes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_informes_acuda',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_mantenimientos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_medios_auxiliares',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_partes_incidencias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_partes_inspeccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_partes_trabajo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_servicios_NFC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_sugerencias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_tareas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permisos_usuario',
        ),
    ]
