# Generated by Django 6.0.5 on 2026-06-25 08:36

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_direccion_enc_user_mail_user_nif_enc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
