# Generated by Django 6.0.5 on 2026-06-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_mail_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
