# Generated by Django 6.0.5 on 2026-06-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_direccion_remove_user_nif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion_enc',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nif_enc',
            new_name='nif',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono_enc',
            new_name='telefono',
        ),
    ]
