# Generated by Django 6.0.5 on 2026-06-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_cuenta_encryptedfilepdf_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.cuenta'),
        ),
    ]
