# Generated by Django 6.0.5 on 2026-06-29 08:07

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='file_key_encription',
            field=encrypted_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
