# Generated by Django 6.0.5 on 2026-06-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cuenta_file_key_encription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrante',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.encryptedfilepdf'),
        ),
    ]
