# Generated by Django 6.0.5 on 2026-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_cuenta'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='users', to='servicios.servicio'),
        ),
    ]
