# Generated by Django 6.0.5 on 2026-05-20 09:40

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('ServicioID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('precio_por_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_semana', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=52, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('es_exterior', models.BooleanField(default=True)),
                ('requiere_gps', models.BooleanField(default=False)),
                ('mail_de_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('clientes', models.ManyToManyField(related_name='servicios', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='empresas.empresa')),
            ],
        ),
    ]
