# Generated by Django 6.0.5 on 2026-06-25 09:17

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mail_de_contacto_enc',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
