# Generated by Django 6.0.5 on 2026-06-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_mail_de_contacto_enc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='mail_de_contacto',
        ),
    ]
