# Generated by Django 6.0.5 on 2026-06-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_servicio_mail_de_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='mail_de_contacto_enc',
            new_name='mail_de_contacto',
        ),
    ]
