# Generated by Django 6.0.5 on 2026-06-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_rename_mail_de_contacto_enc_servicio_mail_de_contacto'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='users.cuenta'),
        ),
    ]
