# Generated by Django 6.0.5 on 2026-06-18 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('SugerenciaID', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('solucionada', 'Solucionada'), ('borrada', 'Borrada')], default='pendiente', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_empresa', to='empresas.empresa')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_referente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_referente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
