# Generated by Django 6.0.5 on 2026-06-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centrales', '0001_initial'),
        ('clientes', '0002_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea_Parte_Trabajo',
            fields=[
                ('LineaParteTrabajoID', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parte_Incidencia',
            fields=[
                ('foto', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ParteIncidenciaID', models.AutoField(primary_key=True, serialize=False)),
                ('texto_incidencia', models.TextField(blank=True, null=True)),
                ('fecha_hora_incidencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parte_Inspeccion',
            fields=[
                ('foto', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ParteInspeccionID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parte_Trabajo',
            fields=[
                ('foto', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ParteTrabajoID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_relevo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informe_Acuda',
            fields=[
                ('foto', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('InformeAcudaID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=255)),
                ('central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centrales.central')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clientes', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_empresas', to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
