# Generated by Django 6.0.5 on 2026-05-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('partes', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informe_acuda',
            name='tecnico_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informe_acuda_tecnico_asociado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe_acuda',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_incidencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clientes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='parte_incidencia',
            name='usuario_asociado_a_incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_incidencia_sobre_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_incidencia',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_inspeccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clientes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='parte_inspeccion',
            name='inspector_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_inspeccion_inspector_asociado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_inspeccion',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clientes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_servicio', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='usuario_relevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_relevo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linea_parte_trabajo',
            name='parte_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_parte_trabajo', to='partes.parte_trabajo'),
        ),
    ]
