# Generated by Django 6.0.5 on 2026-07-01 07:23

import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0002_initial'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe_acuda',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cuenta', to='users.cuenta'),
        ),
        migrations.AddField(
            model_name='linea_parte_trabajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parte_incidencia',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cuenta', to='users.cuenta'),
        ),
        migrations.AddField(
            model_name='parte_inspeccion',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cuenta', to='users.cuenta'),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cuenta', to='users.cuenta'),
        ),
        migrations.AlterField(
            model_name='linea_parte_trabajo',
            name='extra_info',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte_incidencia',
            name='texto_incidencia',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte_inspeccion',
            name='descripcion',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte_trabajo',
            name='observaciones',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
