# Generated by Django 6.0.5 on 2026-07-01 07:58

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0003_informe_acuda_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_acuda',
            name='descripcion',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linea_parte_trabajo',
            name='actividad',
            field=models.CharField(blank=True, choices=[('Inicio', 'Inicio de Actividad'), ('Sin novedad', 'Sin Novedad'), ('Incidencia', 'Incidencia'), ('Finalización', 'Fin del Servicio'), ('Otros', 'Otros'), ('Relevo', 'Relevo de Personal')], max_length=255, null=True),
        ),
    ]
