# Generated by Django 6.0.5 on 2026-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_alter_informe_acuda_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_parte_trabajo',
            name='fecha_registrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='fecha_finalizacion_registrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='fecha_inicio_registrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
