# Generated by Django 6.0.5 on 2026-07-06 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0005_linea_parte_trabajo_fecha_registrada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe_acuda',
            name='tecnico_asociado',
        ),
        migrations.RemoveField(
            model_name='parte_incidencia',
            name='usuario_asociado_a_incidencia',
        ),
        migrations.RemoveField(
            model_name='parte_inspeccion',
            name='inspector_asociado',
        ),
        migrations.AddField(
            model_name='informe_acuda',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_incidencia',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_inspeccion',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='fecha_hora_relevo_registrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte_trabajo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
