# Generated by Django 6.0.5 on 2026-06-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0001_initial'),
        ('users', '0016_alter_cuadrante_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacion',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegaciones', to='users.cuenta'),
        ),
    ]
